# Configuração do banco H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Criar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console